### ISSUE TITLE
Organize your folder structure of repo

### ISSUE THREAD

**Issue by elias117** [duanegero/CoachDee-Website#3]
Your website should have the following folder structure. 

```TEXT
CoachDee/
│
├── index.html
│
├── html/
│   ├── html1.html
│   ├── html2.html
│   ├── html3.html
│   └── and_so_on.html
│
├── css/
│   ├── styles.css
```

You need to have your Home.html which is the page that is shown when we go to the initial website. This is known as the index and needs to be named ```index.html``` I also recommend that you place all other webpages inside an HTML directory like shown. You can name them whatever you like I have named them html1 html2, etc.

**Comment by duanegero** [comment]
Made changes to the files/folders everything should look correct now.
